### PR TITLE
EitherT MonadTrans instance and generics reorder

### PR DESCRIPTION
**Pull request by 1Jajen1**
Changed `EitherT<F, A, B>` -> `EitherT<A, F, B>`.

Same reasons as #23 

This branch fails because the `EitherT` from `arrow-test` does not have this change and thus it refuses to compile. We really do need to change how `arrow-test` is distributed somehow @rachelcarmena. I think this is another confimation for the problems noted in https://github.com/arrow-kt/arrow-core/pull/23, `arrow-test`.

### CODE REVIEW

**Comment by rachelcarmena** [comment]
Hi @1Jajen1! I changed the build check and now I get the same error:

```
e: /home/runner/work/arrow-incubator/arrow-test/arrow-test/src/main/kotlin/arrow/test/generators/GenK.kt: (116, 41): Type inference failed. Expected type mismatch: inferred type is Gen<EitherT<L, F, R>> but Gen<Kind<EitherTPartialOf<F, L> /* = Kind<Kind<ForEitherT, F>, L> */, R>> was expected
```
if I add manually Arrow Test as another sub-project in Arrow Incubator (like the mono-repo). I hope the new build check is useful as a workaround until Arrow Test is "re-organized".

**Comment by 1Jajen1** [comment]
Yup that is the other issue with having `arrow-test` separate. I need to change that in `arrow-test` first, which will break this module, and then merge this pr, which is why this is draft only atm ^^ This is the only of the generic-reorder prs that needs to do that though. The others should work fine with `arrow-test`

**Comment by 1Jajen1** [comment]
But good to see that we have a workaround ^^ I'll check if lazyAp builds right away, that would pretty much confirm it works ^^

**Comment by 1Jajen1** [comment]
This and all the other reorder prs will build fine once #35 is merged.

**Pull request merged**
